### ISSUE TITLE
Impossible to set PK on Adwords Reports

### ISSUE THREAD

**Issue by Jude188** [singer-io/tap-adwords#57]
Hi all,

This is an issue which I've noticed across a few taps but first here so I'll raise the issue here and take it from there.

In my use case I am pulling static reports from various taps and using a target to store them in a database. Because the reports are static I know what the primary key (PK) should be. I had anticipated that I should be able to set the PK for the Singer target to use by either manually setting `key_properties` in the `CatalogEntry`'s schema or probably more sensibly (as the schema should probably remain static/read-only) in the metadata of the stream in `table-key-properties` as documented  [here](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md#metadata). This seems sensible to me as the metadata is the place for user defined behaviour if I understand the intention correctly.

However, the way this tap (and others) is written precludes this. 

When a `sync` is run this tap seems to regenerate all of the schemas from the API.  This means that any change such as adding `key_properties` to the schema will not be passed onto the target. This is, I suppose, reasonable in case the API has changed. 

It is also not possible to set `table-key-properties` as the metadata is not passed to the target. However, this could be solved by adjusting [this line](https://github.com/singer-io/tap-adwords/blob/4db1a16cf4631ddef19aed4157bee830bd408381/tap_adwords/__init__.py#L207) to instead read the `table-key-properties` if they exist and use them. Something like:

```python
primary_keys = metadata.get(stream_metadata, (), 'table-key-properties') or []
```

I've also noticed that the same issue applies to other taps including `tap-bing-ads`. Please do let me know what your thought's on this issue are.

**Comment by luandy64** [comment]
I can't speak for the other taps about this issue. But for `tap-adwords` I believe the reason we say `primary_keys = []` is because we don't always know what the primary key is.

I think your suggestion here (`primary_keys = metadata.get(stream_metadata, (), 'table-key-properties') or []`) is reasonable. 

I think we shouldn't use `table-key-properties` as the key though.

If you look at the [Singer Spec](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md#metadata), there's this line:
> Certain metadata should be written and read by a tap. This metadata is known as discoverable metadata

So because Singer has reserved `table-key-properties` as a `discoverable` piece of metadata, you adding `table-key-properties` to the `catalog` after Discovery mode runs conflicts with the fact that the tap should've written this. 

All of that to say, let's make a new metadata keyword that only this tap understands. Something like `tap-adwords.report-key-properties`. Then we can add this keyword to the `catalog` with the static values you know. And finally, #58 can be changed to use `tap-adwords.report-key-properties` instead of `table-key-properties` and everything should just work just like how #58 works for you now.

**Comment by Jude188** [comment]
Okay, I've made you changes you've requested in #58. Fingers crossed it can be merged and released soon!

Any suggestions about what to do with the same issue in `tap-bing-ads`? I'll happily open an Issue there if you're able to see that it does get some attention in your eng team. I'm sure you're aware of some of the struggles people from the community have had getting issues to your attention and starting discussions. I'm sure you're all very busy so it is of course understandable! (I'm busy too!!)

**Comment by luandy64** [comment]
I would open an issue on the `tap-bing-ads` repo and the card will get prioritized 👍
